site_name: FastTCP
site_url: https://goabonga.github.io/FastTCP
repo_url: https://github.com/goabonga/FastTCP
repo_name: goabonga/FastTCP

theme:
  name: material
  logo: img/FastTCP.svg
  favicon: img/FastTCP.svg
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_pages.py
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            show_root_heading: false
            show_root_full_path: false
            show_source: true
            separate_signature: true
            show_signature_annotations: true
            group_by_category: true
            members_order: "source"
            filters: []
            docstring_style: "google"
            merge_init_into_class: true
            show_submodules: true

watch:
  - src/fasttcp

extra:
  version: !ENV [DOC_VERSION, "dev"]

nav:
  - Home: index.md
  - API Reference: mkdocstrings.md
  - Code of Conduct: code_of_conduct.md
  - License: license.md
  - Changelog: changelog.md
  